Fix the gitlint config error due to invalid character
This patch fixes the gitlint config file error:

Error: Source contains parsing errors: '/.gitlint' [line 52]: '~ \n' [line 53]: '~ \n'